name: Deploy to Prod

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  test_and_deploy:
    name: Test and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Github repo
        uses: actions/checkout@v2

      - name: Install dependencies and build release
        run: yarn && yarn build

      - name: Run unit tests
        run: yarn test

      # - name: Run cypress tests
      #   uses: cypress-io/github-action@v2
      #   with:
      #     start: yarn start
      #   env:
      #     MONGODB_URI: ${{ secrets.MONGODB_URI_DEV }} # TODO: REMOVE THIS ONCE WE HAVE A PROD ENV

      - uses: actions/setup-node@v1
        with:
          node-version: "14"
          registry-url: https://registry.npmjs.org/

      - name: Deploy to Vercel (prod)
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-args: --prod

      - name: Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_SEMVER_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
